#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

#set_property DRIVE 12 [get_ports {Output[15]}]
#set_property DRIVE 12 [get_ports {Output[14]}]
#set_property DRIVE 12 [get_ports {Output[13]}]
#set_property DRIVE 12 [get_ports {Output[12]}]
#set_property DRIVE 12 [get_ports {Output[11]}]
#set_property DRIVE 12 [get_ports {Output[10]}]
#set_property DRIVE 12 [get_ports {Output[9]}]
#set_property DRIVE 12 [get_ports {Output[8]}]
#set_property DRIVE 12 [get_ports {Output[7]}]
#set_property DRIVE 12 [get_ports {Output[6]}]
#set_property DRIVE 12 [get_ports {Output[5]}]
#set_property DRIVE 12 [get_ports {Output[4]}]
#set_property DRIVE 12 [get_ports {Output[3]}]
#set_property DRIVE 12 [get_ports {Output[2]}]
#set_property DRIVE 12 [get_ports {Output[1]}]
#set_property DRIVE 12 [get_ports {Output[0]}]
#set_property PACKAGE_PIN L1 IOSTANDARD LVCMOS33 [get_ports {Output[15]}]
#set_property PACKAGE_PIN P1 IOSTANDARD LVCMOS33 [get_ports {Output[14]}]
#set_property PACKAGE_PIN N3 IOSTANDARD LVCMOS33 [get_ports {Output[13]}]
#set_property PACKAGE_PIN P3 IOSTANDARD LVCMOS33 [get_ports {Output[12]}]
#set_property PACKAGE_PIN U3 IOSTANDARD LVCMOS33 [get_ports {Output[11]}]
#set_property PACKAGE_PIN W3 IOSTANDARD LVCMOS33 [get_ports {Output[10]}]
#set_property PACKAGE_PIN V3 IOSTANDARD LVCMOS33 [get_ports {Output[9]}]
#set_property PACKAGE_PIN V13 IOSTANDARD LVCMOS33 [get_ports {Output[8]}]
#set_property PACKAGE_PIN V14 IOSTANDARD LVCMOS33 [get_ports {Output[7]}]
#set_property PACKAGE_PIN U14 IOSTANDARD LVCMOS33 [get_ports {Output[6]}]
#set_property PACKAGE_PIN U15 IOSTANDARD LVCMOS33 [get_ports {Output[5]}]
#set_property PACKAGE_PIN W18 IOSTANDARD LVCMOS33 [get_ports {Output[4]}]
#set_property PACKAGE_PIN V19 IOSTANDARD LVCMOS33 [get_ports {Output[3]}]
#set_property PACKAGE_PIN U19 IOSTANDARD LVCMOS33 [get_ports {Output[2]}]
#set_property PACKAGE_PIN E19 IOSTANDARD LVCMOS33 [get_ports {Output[1]}]
#set_property PACKAGE_PIN U16 IOSTANDARD LVCMOS33 [get_ports {Output[0]}]

#set_property PACKAGE_PIN T17 [get_ports clk]
#set_property PACKAGE_PIN T18 [get_ports reset]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property IOSTANDARD LVCMOS33 [get_ports {Output[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Output[0]}]

set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports reset]


set_property PACKAGE_PIN L1 [get_ports {Output[15]}]
set_property PACKAGE_PIN P1 [get_ports {Output[14]}]
set_property PACKAGE_PIN N3 [get_ports {Output[13]}]
set_property PACKAGE_PIN P3 [get_ports {Output[12]}]
set_property PACKAGE_PIN U3 [get_ports {Output[11]}]
set_property PACKAGE_PIN W3 [get_ports {Output[10]}]
set_property PACKAGE_PIN V3 [get_ports {Output[9]}]
set_property PACKAGE_PIN V13 [get_ports {Output[8]}]
set_property PACKAGE_PIN V14 [get_ports {Output[7]}]
set_property PACKAGE_PIN U14 [get_ports {Output[6]}]
set_property PACKAGE_PIN U15 [get_ports {Output[5]}]
set_property PACKAGE_PIN W18 [get_ports {Output[4]}]
set_property PACKAGE_PIN V19 [get_ports {Output[3]}]
set_property PACKAGE_PIN U19 [get_ports {Output[2]}]
set_property PACKAGE_PIN E19 [get_ports {Output[1]}]
set_property PACKAGE_PIN U16 [get_ports {Output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T17 [get_ports clk]


